// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default'];
		ElAvatar: typeof import('element-plus/es')['ElAvatar'];
		ElBadge: typeof import('element-plus/es')['ElBadge'];
		ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb'];
		ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem'];
		ElButton: typeof import('element-plus/es')['ElButton'];
		ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup'];
		ElCard: typeof import('element-plus/es')['ElCard'];
		ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
		ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup'];
		ElCol: typeof import('element-plus/es')['ElCol'];
		ElCollapse: typeof import('element-plus/es')['ElCollapse'];
		ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem'];
		ElColorPicker: typeof import('element-plus/es')['ElColorPicker'];
		ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
		ElDescriptions: typeof import('element-plus/es')['ElDescriptions'];
		ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem'];
		ElDialog: typeof import('element-plus/es')['ElDialog'];
		ElDropdown: typeof import('element-plus/es')['ElDropdown'];
		ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
		ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
		ElForm: typeof import('element-plus/es')['ElForm'];
		ElFormItem: typeof import('element-plus/es')['ElFormItem'];
		ElIcon: typeof import('element-plus/es')['ElIcon'];
		ElImage: typeof import('element-plus/es')['ElImage'];
		ElInput: typeof import('element-plus/es')['ElInput'];
		ElMenu: typeof import('element-plus/es')['ElMenu'];
		ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
		ElOption: typeof import('element-plus/es')['ElOption'];
		ElPagination: typeof import('element-plus/es')['ElPagination'];
		ElPopover: typeof import('element-plus/es')['ElPopover'];
		ElProgress: typeof import('element-plus/es')['ElProgress'];
		ElRow: typeof import('element-plus/es')['ElRow'];
		ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
		ElSelect: typeof import('element-plus/es')['ElSelect'];
		ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
		ElTable: typeof import('element-plus/es')['ElTable'];
		ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
		ElTabPane: typeof import('element-plus/es')['ElTabPane'];
		ElTabs: typeof import('element-plus/es')['ElTabs'];
		ElTag: typeof import('element-plus/es')['ElTag'];
		ElTimeline: typeof import('element-plus/es')['ElTimeline'];
		ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem'];
		ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect'];
		ElTooltip: typeof import('element-plus/es')['ElTooltip'];
		ElTree: typeof import('element-plus/es')['ElTree'];
		ElUpload: typeof import('element-plus/es')['ElUpload'];
		Guide: typeof import('./components/Guide/index.vue')['default'];
		HeaderSearch: typeof import('./components/HeaderSearch/index.vue')['default'];
		IndexMy: typeof import('./components/Com/list/src/index-my.vue')['default'];
		LangSelect: typeof import('./components/LangSelect/index.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		ScreenFull: typeof import('./components/ScreenFull/index.vue')['default'];
		SelectColor: typeof import('./components/SelectColor/index.vue')['default'];
		Src: typeof import('./components/Com/calendar/src/index.vue')['default'];
		SvgIcon: typeof import('./components/SvgIcon/index.vue')['default'];
		TagsView: typeof import('./components/TagsView/index.vue')['default'];
		ThemeSelect: typeof import('./components/ThemeSelect/index.vue')['default'];
		Trash: typeof import('./components/Trash/index.vue')['default'];
	}
	export interface ComponentCustomProperties {
		vLoading: typeof import('element-plus/es')['ElLoadingDirective'];
	}
}
